

export const TRANSLATIONS = {
    en: {
        title: "NINE-GRID",
        subtitle: "BATTLER",
        newGame: "NEW GAME",
        continue: "CONTINUE",
        settings: "SETTINGS",
        help: "HELP",
        version: "v1.0.0 • Auto-Save Enabled",
        backToMenu: "Back to Menu",
        manualTitle: "Battle Manual",
        basics: "Basics",
        basicsText: [
            "Deploy units on your 3x3 grid (Left Side).",
            "You cannot deploy more units than the enemy.",
            "Units attack automatically based on speed and formation.",
            "Units gain Energy when attacking or taking damage. At 100 Energy, they cast their Skill."
        ],
        targeting: "Targeting Logic",
        targetingText: [
            "Units prioritize targets in this order:",
            "Enemies in the same row.",
            "The front-most enemy in that row.",
            "If row is empty, the closest adjacent row."
        ],
        roles: "Roles",
        level: "LEVEL",
        best: "BEST",
        turn: "TURN",
        spd: "SPD",
        battle: "BATTLE",
        formation: "FORMATION",
        matchup: "MATCHUP",
        confirm: "CONFIRM",
        power: "POWER",
        exit: "EXIT",
        nextLevel: "NEXT LEVEL",
        tryAgain: "TRY AGAIN",
        reset: "RESET",
        barracks: "Barracks",
        units: "Units",
        deployLimit: "Deployment limit reached!",
        clickToAdd: "Click to add units. Drag on grid to move.",
        battleProgress: "Battle in Progress",
        victory: "VICTORY",
        defeat: "DEFEAT",
        levelCleared: "Level Cleared!",
        battleLog: "Battle Log",
        saveExit: "Save & Exit",
        skip: "SKIP",
        settingsTitle: "Settings",
        theme: "Theme",
        language: "Language",
        saved: "Game Saved!",
        saveFailed: "Failed to save game.",
        loadFailed: "Failed to load save file.",
        placeUnit: "Place at least one unit!",
        tooManyUnits: "You have too many units!",
        speedMsg: "Speed: Player {p} vs Enemy {e}.",
        firstMsg: ">> {side} Team Attacks First!",
        startMsg: "Battle Start!",
        levelMsg: "Level {l} Started! Enemy Power: {p}%",
        healedMsg: "{a} healed {t} for {v} HP!",
        skillHealMsg: "{a} used {s} to heal {t} for {v} HP!",
        attackMsg: "{a} used {s} on {t} for {v} dmg!",
        active: "Active",
        unitInfo: {
            KNIGHT: { name: 'Iron Guard', desc: 'High defense tank.', skill: 'Fortress' },
            BERSERKER: { name: 'Berserker', desc: 'Balanced fighter.', skill: 'Rage Strike' },
            MAGE: { name: 'Pyromancer', desc: 'High damage, low HP.', skill: 'Fireball' },
            ASSASSIN: { name: 'Ninja', desc: 'Very fast, high crit.', skill: 'Shadow Step' },
            PRIEST: { name: 'Cleric', desc: 'Heals allies.', skill: 'Divine Heal' },
        } as Record<string, {name: string, desc: string, skill: string}>,
        roleDesc: {
            TANK: "High HP/DEF. Place in front.",
            WARRIOR: "Balanced Offense/Defense.",
            MAGE: "High ATK, Low DEF. Good against Tanks.",
            ASSASSIN: "Fast, High Crit. Good against Mages.",
            SUPPORT: "Heals lowest HP ally."
        } as Record<string, string>
    },
    zh: {
        title: "九宫格",
        subtitle: "自动对战",
        newGame: "新的游戏",
        continue: "继续游戏",
        settings: "游戏设置",
        help: "帮助手册",
        version: "v1.0.0 • 自动存档已启用",
        backToMenu: "返回主菜单",
        manualTitle: "战斗手册",
        basics: "基础规则",
        basicsText: [
            "在左侧3x3网格上部署你的单位。",
            "上阵单位数量不能超过敌方。",
            "单位根据速度和阵型自动攻击。",
            "攻击或受到伤害时获得能量。能量达到100时释放技能。"
        ],
        targeting: "索敌逻辑",
        targetingText: [
            "单位优先攻击以下目标：",
            "同一行的敌人。",
            "该行最靠前的敌人。",
            "如果该行从缺，则攻击最近的相邻行。"
        ],
        roles: "职业介绍",
        level: "关卡",
        best: "最高记录",
        turn: "回合",
        spd: "速度",
        battle: "开始战斗",
        formation: "布阵",
        matchup: "对阵",
        confirm: "布阵完成",
        power: "战力",
        exit: "退出",
        nextLevel: "下一关",
        tryAgain: "再试一次",
        reset: "重置",
        barracks: "兵营",
        units: "单位",
        deployLimit: "已达到部署上限！",
        clickToAdd: "点击添加单位，拖拽移动位置。",
        battleProgress: "战斗进行中",
        victory: "胜利",
        defeat: "失败",
        levelCleared: "关卡通过！",
        battleLog: "战斗日志",
        saveExit: "保存并退出",
        skip: "跳过",
        settingsTitle: "设置",
        theme: "主题颜色",
        language: "语言选择",
        saved: "游戏已保存！",
        saveFailed: "保存失败。",
        loadFailed: "读取存档失败。",
        placeUnit: "请至少部署一个单位！",
        tooManyUnits: "单位数量过多！",
        speedMsg: "速度: 我方 {p} vs 敌方 {e}。",
        firstMsg: ">> {side} 率先出手！",
        startMsg: "战斗开始！",
        levelMsg: "第 {l} 关开始！ 敌方战力: {p}%",
        healedMsg: "{a} 为 {t} 恢复了 {v} 点生命！",
        skillHealMsg: "{a} 使用 {s} 为 {t} 恢复了 {v} 点生命！",
        attackMsg: "{a} 对 {t} 使用 {s} 造成 {v} 点伤害！",
        active: "当前行动",
        unitInfo: {
            KNIGHT: { name: '钢铁卫士', desc: '高防御坦克。', skill: '堡垒' },
            BERSERKER: { name: '狂战士', desc: '攻守兼备。', skill: '狂暴打击' },
            MAGE: { name: '烈焰法师', desc: '高攻脆皮。', skill: '火球术' },
            ASSASSIN: { name: '忍者', desc: '高速暴击。', skill: '暗影步' },
            PRIEST: { name: '牧师', desc: '治疗友军。', skill: '神圣治愈' },
        },
        roleDesc: {
            TANK: "高生命/防御。建议前排。",
            WARRIOR: "攻守平衡。",
            MAGE: "高攻击，低防御。克制坦克。",
            ASSASSIN: "高速，高暴击。克制法师。",
            SUPPORT: "治疗生命值最低的友军。"
        }
    }
};
